### ISSUE TITLE
変換元のtwbが開かない

### ISSUE THREAD

**Issue by Y-Shima** [taiga/TwbColumnRenamer#3]
カラム名の変換が一括で出来ると便利ですね。ありがたく使用させて頂きたいです。
変換元のtwbが開きませんでした。ご対応いただけると嬉しいです。
よろしくお願い致します。

【環境】
Tableau Desktop 10.3.1 win64
Chrome バージョン: 59.0.3071.115（Official Build） （64 ビット）

【twbファイル】
データソースは、BigQueryに接続しています。
”クライアントID”だけカラム名を変換してあります。
[sinnpakusu.zip](https://github.com/taiga/TwbColumnRenamer/files/1181755/sinnpakusu.zip)

【同じ環境で確認したこと】
sample.twbを開く→OK
エクスポートしたcvsをデータソースとして接続して、twbに保存したファイル→OK

**Comment by taiga** [comment]
@Y-Shima 
怪しい箇所に手を入れてみました。https://github.com/taiga/TwbColumnRenamer/commit/44c113a57a62fca707687185f85ae8fd9ea6ee7b
下記ファイルを、お手元の Tableau Desktop で開けるか、お試しいただけますでしょうか。
( 大人の事情で Tableau Desktop 環境が手元に無い状況なので `.twb` の読み書き不具合のみ修正確認しています )
↓
[sinnpakusu_replace.zip](https://github.com/taiga/TwbColumnRenamer/files/1182164/sinnpakusu_replace.zip)

問題なさそうであれば、 github.io に置いてあるアプリも更新します。

**Comment by Y-Shima** [comment]
迅速な対応、ありがとうございます。
添付して頂いたワークブックはTableau Desktopで開けました。

**Comment by taiga** [comment]
@Y-Shima 
ご確認ありがとうございます。
DEMO 版を `v1.0.1` にアップデートしました。
https://github.com/taiga/TwbColumnRenamer/releases/tag/v1.0.1

画面に `(v1.0.1)` と表記されていることをご確認の上、お試しください。
https://taiga.github.io/tableau/TwbColumnRenamer/

**Comment by taiga** [comment]
以前バージョンでは、複数のデータソースを扱う `.twb` には対応していなかったのですが、今回の修正で `<datasources>` 要素内にある ` <datasource>` 要素の順番に、全カラム名をフラットに出力するようになりました。

頂いたサンプルですと、
```
[clientId]
…
[time_str]
[clientId]
…
[time_str]
[clientId]
…
[value]
[clientId]
…
[targetDateTime]
```

という具合に出力するはずですが、上記のように `.twb` の中に『データソースが異なる同一のカラム名  ( `[clientId]` など ) 』が複数含まれる場合、「見た目」的に、カラムの所属データソースを確認することができません。その点のみご注意ください。 ( UI の見直しも検討したほうが良いかもしれませんね )

**Comment by Y-Shima** [comment]
迅速な対応、ありがとうございます。
使用してみたところ、変換されるカラムがずれました。
あと、すみません、データソースは試行錯誤の上で複数追加してしまっていました。１データソース、４カラムのシンプルなワークブックを添付させて頂きます。ご対応いただけると嬉しいです。
[sinnpakusu3.zip](https://github.com/taiga/TwbColumnRenamer/files/1182450/sinnpakusu3.zip)

追記：
ごめんなさい、v1.0で１つのデータソースのワークブックでしたら、うまく変換できました！
お手を煩わせてしまい申し訳ないです。

**Comment by taiga** [comment]
@Y-Shima 
スミマセン。凡ミスを仕込んでしまったので修正しました。 (https://github.com/taiga/TwbColumnRenamer/commit/3b7eeb6966351bfa1d4a83a175a00baa4bb76bc9)
`v1.0.2` にアップデートしましたので、再度ご確認をお願いいたします。

https://github.com/taiga/TwbColumnRenamer/releases/tag/v1.0.2

画面に `(v1.0.2)` と表記されていることをご確認の上、お試しください。
https://taiga.github.io/tableau/TwbColumnRenamer/

**Comment by Y-Shima** [comment]
1.0.2で確認しました。複数のデータソースを使用するワークブックで開きました。ありがとうございます！
