### ISSUE TITLE
全てDimensionになってしまう

### ISSUE THREAD

**Issue by gasakamaki** [taiga/TwbColumnRenamer#5]
有用なツールの公開ありがとうございます。

Google BigQuery上のTableに接続したtabファイルの変換を行いました。

接続時には自動的にメジャーに指定された、word_countおよびcorpus_dateが、
Webで公開いただいているデモページで全項目を日本語名に一括変換を掛けたところ、
全項目がディメンションとして出力されました。

ご対応いただけると大変助かります。

[test_BQ_shakespeare.zip](https://github.com/taiga/TwbColumnRenamer/files/1331451/test_BQ_shakespeare.zip)

・対象テーブル
BigQuery - publicdata - samples - shakespeare

・対象テーブル（データソース）内の列定義
word : STRING
word_count : INTEGER
corpus : STRING
corpus_date :  INTEGER

【動作環境】
●PC
・Windows 7 
・Chrome
・Tableau 10.3.2

●一括変換アプリ
・公開いただいているデモページ

**Comment by taiga** [comment]
@gasakamaki
`.twb` ファイルに、リネーム対象のカラム ( `<column>` 要素 ) が存在しなかったとき、 role 値を `'dimension'` と決め打ちしていた箇所を見直しました。  https://github.com/taiga/TwbColumnRenamer/commit/6594b5ca51ca611d93af45756fba6020ad0ce579

仕様が公開されていないため、ロジック的に本当に正しいかは分かりかねますが、 `v1.0.3` に更新しましたので、お試しください。
https://taiga.github.io/tableau/TwbColumnRenamer/

**Comment by gasakamaki** [comment]
@taiga さん

早々のご対応いただきありがとうございます。

サンプルの.twbおよび実際の.twbファイルで試してみましたが、
期待通りの動きとなりました！

ありがとうございました！
